# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
    ]
